services:
  - type: web
    name: Mudrika
    env: python
    buildCommand: "pip3 install -r requirements.txt && python manage.py migrate --no-input"
    startCommand: "gunicorn wsgi:application"
    autoDeploy: true
