services:
  - type: web
    name: Mudrika
    env: python
    buildCommand: "pip3 install -r requirements.txt && python manage.py migrate --no-input"
    startCommand: "python manage.py runserver 0.0.0.0:3000"
    autoDeploy: true
