# Generated by Django 4.0.5 on 2022-06-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MudrikaApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileDummy',
            fields=[
                ('acc_address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=24)),
                ('type_phrase', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
