# Generated by Django 3.2.5 on 2022-07-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MudrikaApi', '0002_userprofiledummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevelKeyDummy',
            fields=[
                ('access_phrase', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('national', 'NATIONAL'), ('state', 'STATE'), ('district', 'DISTRICT')], default='district', max_length=8)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=42, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
