# Generated by Django 3.2.5 on 2022-07-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MudrikaApi', '0003_accesslevelkeydummy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessLevelKeyDummy',
            new_name='AccessLevelTokenDummy',
        ),
    ]
