# Generated by Django 3.2.5 on 2022-07-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MudrikaApi', '0005_auto_20220704_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='Sudu',
        ),
    ]
