# Generated by Django 3.2.5 on 2022-12-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MudrikaApi', '0006_auto_20220713_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('wallet_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('district', models.CharField(max_length=35)),
                ('mobile_number', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewConsignmentData',
            fields=[
                ('cons_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('con_name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=60)),
                ('sender', models.CharField(max_length=45)),
                ('receiver', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofilesignupdata',
            options={},
        ),
    ]
