# Generated by Django 3.2.5 on 2023-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MudrikaApi', '0007_auto_20221202_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfileSignUpData',
            fields=[
                ('walletid', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('aadharngoid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('profileimg', models.CharField(max_length=255)),
                ('voltype', models.CharField(max_length=32)),
            ],
        ),
    ]
