# Generated by Django 3.2.5 on 2023-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MudrikaApi', '0008_volunteerprofilesignupdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerActivityData',
            fields=[
                ('walletid', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('imageLink', models.URLField()),
            ],
        ),
    ]
