# Generated by Django 3.2.5 on 2023-05-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MudrikaApi', '0009_volunteeractivitydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeractivitydata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
